# Initial configuration

In [1]:
%load_ext autoreload
%autoreload 2

import os
os.chdir("/nfs/turbo/coe-chaijy/sstorks/simulation_informed_pcr4nlu/TRAVEl")
from travel import init_travel
init_travel()

# Old

In [4]:
from travel.model.metrics import consistency_metrics_caption
from pprint import pprint

procedure_descriptions = [
    "Put the spatula on the cutting board",
    "Trim the fence branches with a lopper shears",
    "Cut the carrot stem with the knife",
    "Pick the half of the dough from the table with your hands",
]

captions = [
    ["This is a photo of a bathroom sink area, where a person is standing next to the sink. The sink is filled with various items, including a cup, a bottle, a spoon, and a bowl. The person is holding a cup, possibly preparing to use the sink or cleaning it. The scene also includes a knife and a pair of scissors, which might be used for cutting or preparing items in the bathroom."],
    ["This is a photo of a person wearing purple gloves and holding a pair of scissors. The person is standing in a grassy area, possibly in a park or a garden. The scissors are open, and the person appears to be preparing to cut something, possibly a plant or a piece of fabric. The scene captures the person's focus on the task at hand."],
    ["This is a photo of a man working on a wooden floor, possibly in a kitchen or a room. He is holding a wooden stick or a plank, possibly a piece of wood or a tool, and appears to be measuring or working on the floor. The man is standing on the floor, and there is a tool nearby, possibly a drill or a measuring device. The scene suggests that the man is either installing or repairing the wooden floor."],
    ["This is a photo of a kitchen scene where a person is preparing doughnuts. There are several doughnuts in various stages of preparation, with some of them being shaped and others being placed on a tray. The doughnuts are spread out on the counter, and the person is working on the doughnut-making process. The kitchen is equipped with a sink and an oven, which are essential tools for the doughnut-making process."],
]

labels = [
    False,
    False,
    True,
    True
]

metrics = consistency_metrics_caption(captions, procedure_descriptions, labels, list(range(len(procedure_descriptions))), [[0.0]] * len(procedure_descriptions))
pprint(metrics)

`low_cpu_mem_usage` was None, now set to True since model is quantized.


['This is a <mask> of a <mask> <mask> <mask>, where a <mask> is <mask> next to the <mask>. The <mask> is <mask> with various <mask>, <mask> a <mask>, a <mask>, a <mask>, and a <mask>. The <mask> is <mask> a <mask>, possibly <mask> to <mask> the <mask> or <mask> it. The <mask> also <mask> a <mask> and a <mask> of <mask>, which might be <mask>d for <mask> or <mask> <mask> in the <mask>.', "This is a <mask> of a <mask> <mask> purple <mask> and <mask> a <mask> of <mask>. The <mask> is <mask> in a grassy <mask>, possibly in a <mask> or a <mask>. The <mask> are open, and the <mask> <mask> to be <mask> to <mask> something, possibly a <mask> or a <mask> of <mask>. The <mask> <mask> the <mask>'s <mask> on the <mask> at <mask>.", 'This is a <mask> of a <mask> <mask> on a <mask>en <mask>, possibly in a <mask> or a <mask>. He is <mask> a <mask>en <mask> or a <mask>, possibly a <mask> of <mask> or a <mask>, and <mask> to be <mask> or <mask> on the <mask>. The <mask> is <mask> on the <mask>, and the

running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 14.92it/s]

{'consistency': 0.034,
 'informativeness': 0.475,
 'metrics_by_example': {0: {'consistency': [array([0.0001905], dtype=float16)],
                            'informativeness': [array([0.03001], dtype=float16)],
                            'relevance': [array([0.006348], dtype=float16)]},
                        1: {'consistency': [array([0.0004964], dtype=float16)],
                            'informativeness': [array([0.00574], dtype=float16)],
                            'relevance': [array([0.0864], dtype=float16)]},
                        2: {'consistency': [array([0.0405], dtype=float16)],
                            'informativeness': [array([0.9116], dtype=float16)],
                            'relevance': [array([0.04443], dtype=float16)]},
                        3: {'consistency': [array([0.0962], dtype=float16)],
                            'informativeness': [array([0.9517], dtype=float16)],
                            'relevance': [array([0.1011], dtype=float16)]}},
 '

In [51]:
from travel.data.vqg import VQGOutputs
from travel.model.metrics import consistency_metrics_vqg
from pprint import pprint

procedure_descriptions = [
    "Put the spatula on the cutting board",
    "Trim the fence branches with a lopper shears",
    "Cut the carrot stem with the knife",
    "Pick the half of the dough from the table with your hands",
]

vqg_outputs = {
    0: VQGOutputs(
        procedure_id=0,
        procedure_description="Put the spatula on the cutting board",
        questions=[
            "Is the spatula on the cutting board?",
            "Is the cutting board empty?",
        ],
        answers_str=["Yes", "No"],
    ),
    1: VQGOutputs(
        procedure_id=1,
        procedure_description="Trim the fence branches with a lopper shears",
        questions=[
            "Are there branches?",
            "Are the lopper shears rusty?",
        ],
        answers_str=["Yes", "No"],
    ),
    2: VQGOutputs(
        procedure_id=2,
        procedure_description="Cut the carrot stem with the knife",
        questions=[
            "Is the carrot in the bag?",
            "Is the knife clean?",
        ],
        answers_str=["Yes", "Yes"],
    ),
    3: VQGOutputs(
        procedure_id=3,
        procedure_description="Pick the half of the dough from the table with your hands",
        questions=[
            "Is half of the dough in someone's hands?",
            "Is half of the dough on the table?",
        ],
        answers_str=["Yes", "Yes"]
    )
}

labels = [
    False,
    False,
    True,
    True
]

procedure_ids = [
    0, 1, 2, 3
]

metrics = consistency_metrics_vqg(vqg_outputs, labels, procedure_ids)
pprint(metrics)

`low_cpu_mem_usage` was None, now set to True since model is quantized.
running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 16.14it/s]

torch.Size([8])
torch.Size([8])
torch.Size([8])
{'consistency': 0.5,
 'informativeness': 0.771,
 'metrics_by_output': {0: {'consistency': [0.893, 0.002],
                           'informativeness': [0.984, 0.053],
                           'relevance': [0.908, 0.046]},
                       1: {'consistency': [0.291, 0.35],
                           'informativeness': [0.611, 0.603],
                           'relevance': [0.476, 0.581]},
                       2: {'consistency': [0.302, 0.367],
                           'informativeness': [0.983, 0.938],
                           'relevance': [0.308, 0.392]},
                       3: {'consistency': [0.942, 0.857],
                           'informativeness': [0.998, 0.996],
                           'relevance': [0.944, 0.861]}},
 'relevance': 0.564}


In [38]:
metrics_old = metrics

In [39]:
pprint(metrics_old)

{'consistency': 0.465,
 'informativeness': 0.626,
 'metrics_by_output': {0: {'consistency': [0.956, 0.003],
                           'informativeness': [0.984, 0.053],
                           'relevance': [0.972, 0.06]},
                       1: {'consistency': [0.358, 0.285],
                           'informativeness': [0.611, 0.603],
                           'relevance': [0.585, 0.472]},
                       2: {'consistency': [0.12, 0.248],
                           'informativeness': [0.355, 0.53],
                           'relevance': [0.339, 0.468]},
                       3: {'consistency': [0.918, 0.832],
                           'informativeness': [0.959, 0.914],
                           'relevance': [0.957, 0.91]}},
 'relevance': 0.595}


# 7/31/2024 - 8/1/2024

In [38]:
from travel.model.nli import NLI_HYPOTHESIS_TEMPLATE

procedure = "In a bowl, add the cut cherry tomatoes"
hypothesis = NLI_HYPOTHESIS_TEMPLATE.format(procedure=procedure)
candidate_question_sets = [
    ['Are there cherry tomatoes in the bowl?', # Yes
     'Are there any cherry tomatoes that are not in the bowl?'], # No
    ['Are the tomatoes in the bowl?', # Yes
     'Are there any tomatoes that are not in the bowl?'], # No
    ['Is there a bowl?', # Yes
     'Is there a cut cherry tomato in the bowl?'], # Yes
    ['Are the cherry tomatoes in a bowl?', # Yes
     "Is the bowl in someone's hand?"] # Yes
]

questions_as_statements_expected = [
    [
        "There are cherry tomatoes in the bowl.",
        "There are not any cherry tomatoes that are not in the bowl.",
    ],
    [
        "The tomatoes are in the bowl.",
        "There are not any tomatoes that are not in the bowl.",
    ],
    [
        "There is a bowl.",
        "There is a cut cherry tomato in the bowl."
    ],
    [
        "There are cherry tomatoes in a bowl.",
        "The bowl is in someone's hand.",
    ]
]

questions_as_statements_unexpected = [
    [
        "There are not cherry tomatoes in the bowl.",
        "There are cherry tomatoes that are not in the bowl.",
    ],
    [
        "The tomatoes are not in the bowl.",
        "There are tomatoes that are not in the bowl.",
    ],
    [
        "There is not a bowl.",
        "There is not a cut cherry tomato in the bowl."
    ],
    [
        "There are not cherry tomatoes in a bowl.",
        "The bowl is not in someone's hand.",
    ]
]

In [2]:
import torch
from transformers import BitsAndBytesConfig, AutoModelForSequenceClassification, AutoTokenizer
import spacy

from travel.model.nli import NLI_MODEL_PATH

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

nli_model = AutoModelForSequenceClassification.from_pretrained(NLI_MODEL_PATH, quantization_config=bnb_config)
nli_tokenizer = AutoTokenizer.from_pretrained(NLI_MODEL_PATH)
nlp = spacy.load("en_core_web_lg")

/home/sstorks/.cache/pypoetry/virtualenvs/travel-nQET-zRt-py3.10/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
`low_cpu_mem_usage` was None, now set to True since model is quantized.


In [3]:
from travel.model.nli import run_nli

def get_entailment_probability(premise, hypothesis):
    probs_expected = run_nli(nli_tokenizer, nli_model, list(zip(premise, hypothesis)))
    return probs_expected[:, 1].numpy()

print(get_entailment_probability(["There is a puppy."], ["There is a dog."]))
print(get_entailment_probability(["There is a puppy."], ["There is a kitten."]))

running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00,  2.06it/s]


[0.9897]


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.16it/s]

[0.2544]


In [41]:
import numpy as np
from pprint import pprint

from travel.model.metrics import mask_verbs_and_nouns

for idx, (qe, qu) in enumerate(zip(questions_as_statements_expected, questions_as_statements_unexpected)):
    print(idx)
    pprint(qe)
    print("==========")
    
    probs_e = get_entailment_probability(qe, [hypothesis] * 2)
    probs_u = get_entailment_probability(qu, [hypothesis] * 2)
    
    negation_based_relevance = np.abs(probs_e - probs_u)
    print("Relevance (negation):")
    pprint(negation_based_relevance)
    
    mask_based_relevance = get_entailment_probability([mask_verbs_and_nouns(t, nlp, nli_tokenizer.mask_token) for t in qe], [hypothesis] * 2)
    print("Relevance (mask):")
    pprint(mask_based_relevance)
    
    print("Informativeness (expected):")
    pprint(probs_e)
    
    print("Informativeness (unexpected):")
    pprint(1.0 - probs_u)
    
    print("")
    

0
['There are cherry tomatoes in the bowl.',
 'There are not any cherry tomatoes that are not in the bowl.']


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.27it/s]


Relevance (negation):
array([0.943 , 0.9185], dtype=float16)


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 14.45it/s]


Relevance (mask):
array([0.5347, 0.1262], dtype=float16)
Informativeness (expected):
array([0.977, 0.928], dtype=float16)
Informativeness (unexpected):
array([0.966, 0.99 ], dtype=float16)

1
['The tomatoes are in the bowl.',
 'There are not any tomatoes that are not in the bowl.']


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.36it/s]


Relevance (negation):
array([0.986, 0.829], dtype=float16)


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.37it/s]


Relevance (mask):
array([0.671 , 0.1438], dtype=float16)
Informativeness (expected):
array([0.9946, 0.8403], dtype=float16)
Informativeness (unexpected):
array([0.991, 0.989], dtype=float16)

2
['There is a bowl.', 'There is a cut cherry tomato in the bowl.']


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.70it/s]


Relevance (negation):
array([0.5586, 0.95  ], dtype=float16)


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.56it/s]


Relevance (mask):
array([0.4731, 0.3987], dtype=float16)
Informativeness (expected):
array([0.5605, 0.968 ], dtype=float16)
Informativeness (unexpected):
array([0.998 , 0.9824], dtype=float16)

3
['There are cherry tomatoes in a bowl.', "The bowl is in someone's hand."]


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.70it/s]


Relevance (negation):
array([0.96  , 0.5444], dtype=float16)


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.45it/s]

Relevance (mask):
array([0.3853, 0.4224], dtype=float16)
Informativeness (expected):
array([0.9707, 0.628 ], dtype=float16)
Informativeness (unexpected):
array([0.9893, 0.9165], dtype=float16)



In [54]:
from travel.model.nli import NLI_HYPOTHESIS_TEMPLATE

# Look into how additional information might come together for "sufficiency" metric

statement1 = "There is a bowl."
statement2 = "There are cherry tomatoes in the bowl."
# statement3 = "There are not cherry tomatoes outside of the bowl."
statement3 = "The bowl is empty."


statements = [
    statement1,
    statement1 + " " + statement2,
    statement1 + " " + statement2 + " " + statement3,
]

procedure = "In a bowl, add the cut cherry tomatoes"
hypothesis = NLI_HYPOTHESIS_TEMPLATE.format(procedure=procedure)

In [55]:
from pprint import pprint

probs = get_entailment_probability(statements, [hypothesis]*3)
pprint(probs)

running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.49it/s]

array([5.645e-01, 8.931e-01, 6.628e-04], dtype=float16)


In [43]:
print("1->2")
probs = get_entailment_probability([statement1], [statement2])
print(probs)
print("")

print("12->3")
probs = get_entailment_probability([statement1 + " " + statement2], [statement3])
print(probs)
print("")

1->2


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 16.27it/s]


[0.4946]

12->3


running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 16.55it/s]

[0.964]



# 8/14/2024

In [2]:
import torch
from transformers import BitsAndBytesConfig, AutoModelForSequenceClassification, AutoTokenizer
import spacy

from travel.model.nli import NLI_MODEL_PATH

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

nli_model = AutoModelForSequenceClassification.from_pretrained(NLI_MODEL_PATH, quantization_config=bnb_config)
nli_tokenizer = AutoTokenizer.from_pretrained(NLI_MODEL_PATH)
nlp = spacy.load("en_core_web_lg")

`low_cpu_mem_usage` was None, now set to True since model is quantized.
/home/sstorks/.cache/pypoetry/virtualenvs/travel-nQET-zRt-py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [12]:
from travel.model.nli import run_nli

def get_entailment_probability(premise, hypothesis):
    probs_expected = run_nli(nli_tokenizer, nli_model, list(zip(premise, hypothesis)))
    return probs_expected[:, 1].numpy()


In [41]:
probs = get_entailment_probability(
    ["The person is not holding a plate in their hand.", "The person is holding a plate in their hand."], 
    ['The procedure "Pick a plate" has been successfully executed.', 'The procedure "Pick a plate" has been successfully executed.']
)
print(probs)

running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 16.06it/s]

[0.09393 0.7163 ]


In [42]:
from travel.model.metrics import entropy
import numpy as np

ents = [1.0 - entropy(p) for p in probs]
relevance = np.abs(probs[0] - probs[1])
info = np.max(ents)

print(ents)
print(relevance)
print(info)
print(relevance * info)

[0.5505005020028562, 0.13939019498439031]
0.6226
0.5505005020028562
0.34271881838556717


# 8/15/2024

Messing with variations in NLI depending on batch size, padding, etc.

In [2]:
import torch
from transformers import BitsAndBytesConfig, AutoModelForSequenceClassification, AutoTokenizer
import spacy

from travel.model.nli import NLI_MODEL_PATH

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

nli_model = AutoModelForSequenceClassification.from_pretrained(NLI_MODEL_PATH, quantization_config=bnb_config)
nli_tokenizer = AutoTokenizer.from_pretrained(NLI_MODEL_PATH)
nlp = spacy.load("en_core_web_lg")

`low_cpu_mem_usage` was None, now set to True since model is quantized.
/home/sstorks/.cache/pypoetry/virtualenvs/travel-nQET-zRt-py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [11]:
from travel.model.nli import run_nli
from pprint import pprint

premise_hypothesis_pairs = [
    ("There is no paper.", 'The procedure "Take the paper" has been successfully executed.'),
    ("There is paper.", 'The procedure "Take the paper" has been successfully executed.'),    
    ("The refrigerator is open.", 'The procedure "Close the refrigerator" has been successfully executed.'),
    ("The refrigerator is closed.", 'The procedure "Close the refrigerator" has been successfully executed.'),
    ("There is no dish in the image.", 'The procedure "Pick a dish" has been successfully executed.'),
    ("There is a dish in the image.", 'The procedure "Pick a dish" has been successfully executed.'),
    ("There is a long pointy pencil in the desk drawer.", 'The procedure "Use the pencil to draw a stick figure" has been successfully executed.'),
    ("There is not a long pointy pencil in the desk drawer.", 'The procedure "Use the pencil to draw a stick figure" has been successfully executed.'),
]
results = run_nli(nli_tokenizer, nli_model, premise_hypothesis_pairs)
pprint(results)

running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 15.71it/s]

tensor([[9.9609e-01, 3.7212e-03],
        [4.2139e-01, 5.7861e-01],
        [1.5833e-01, 8.4180e-01],
        [1.0431e-04, 1.0000e+00],
        [9.8975e-01, 1.0406e-02],
        [5.0098e-01, 4.9902e-01],
        [7.0215e-01, 2.9761e-01],
        [9.9707e-01, 2.7103e-03]], dtype=torch.float16)


In [10]:
results1 = results
pprint(results1)

tensor([[9.9609e-01, 3.7212e-03],
        [4.2139e-01, 5.7861e-01],
        [1.5833e-01, 8.4180e-01],
        [1.0431e-04, 1.0000e+00],
        [9.8975e-01, 1.0406e-02],
        [5.0098e-01, 4.9902e-01]], dtype=torch.float16)


In [12]:
results2 = results
pprint(results2)

tensor([[9.9609e-01, 3.7212e-03],
        [4.2139e-01, 5.7861e-01],
        [1.5833e-01, 8.4180e-01],
        [1.0431e-04, 1.0000e+00],
        [9.8975e-01, 1.0406e-02],
        [5.0098e-01, 4.9902e-01],
        [7.0215e-01, 2.9761e-01],
        [9.9707e-01, 2.7103e-03]], dtype=torch.float16)


In [2]:
import torch
from transformers import AutoModelForVision2Seq, AutoProcessor, BitsAndBytesConfig

VLM_NAME = "llava-hf/llava-1.5-7b-hf"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

vlm = AutoModelForVision2Seq.from_pretrained(VLM_NAME, 
                                            quantization_config=bnb_config)
vlm_processor = AutoProcessor.from_pretrained(VLM_NAME)
vlm_processor.tokenizer.padding_side = "left"
vlm_processor.tokenizer.pad_token_id = vlm_processor.tokenizer.eos_token_id

`low_cpu_mem_usage` was None, now set to True since model is quantized.


Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [8]:
from travel.model.metrics import rephrase_question_answer

rep = rephrase_question_answer(
    ["Is the fridge opened?", 
     "Is the fridge opened?", 
     "Is there a fridge somewhere in the image?", 
     "Is there a fridge somewhere in the image?",
     "Is there a dog under the chair next to the desk behind the fridge in the kitchen?"],
    ["Yes", "No", "Yes", "No", "Yes"],
    vlm_processor.tokenizer,
    vlm.language_model,
)
print(rep)

running generation (cuda:0): 100%|██████████| 1/1 [00:02<00:00,  2.60s/it]

[' The fridge is opened.', ' The fridge is not opened.', ' There is a fridge in the image.', ' There is no fridge in the image.', ' There is a dog under the chair next to the desk behind the fridge in the kitchen.']


In [5]:
rep1 = rep
print(rep1)

[' The fridge is opened.']


In [7]:
rep2 = rep
print(rep2)

[' The fridge is opened.', ' The fridge is not opened.', ' There is a fridge in the image.', ' There is no fridge in the image.']


# 8/16/2024

Checking why informativeness is sometimes not the same as informativeness_marginal when there are no previous questions.

In [2]:
import torch
from transformers import BitsAndBytesConfig, AutoModelForSequenceClassification, AutoTokenizer
import spacy

from travel.model.nli import NLI_MODEL_PATH

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

nli_model = AutoModelForSequenceClassification.from_pretrained(NLI_MODEL_PATH, quantization_config=bnb_config)
nli_tokenizer = AutoTokenizer.from_pretrained(NLI_MODEL_PATH)
nlp = spacy.load("en_core_web_lg")

`low_cpu_mem_usage` was None, now set to True since model is quantized.
/home/sstorks/.cache/pypoetry/virtualenvs/travel-nQET-zRt-py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [3]:
import torch
from transformers import AutoModelForVision2Seq, AutoProcessor, BitsAndBytesConfig

VLM_NAME = "llava-hf/llava-1.5-7b-hf"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

vlm = AutoModelForVision2Seq.from_pretrained(VLM_NAME, 
                                            quantization_config=bnb_config)
vlm_processor = AutoProcessor.from_pretrained(VLM_NAME)
vlm_processor.tokenizer.padding_side = "left"
vlm_processor.tokenizer.pad_token_id = vlm_processor.tokenizer.eos_token_id

`low_cpu_mem_usage` was None, now set to True since model is quantized.


Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [10]:
from travel.model.metrics import question_coherence_metrics_nli
from pprint import pprint

metrics = question_coherence_metrics_nli(
    nli_tokenizer,
    nli_model,
    vlm_processor.tokenizer,
    vlm.language_model,
    answers=["Yes"],
    procedures=["Cut a portion of the concrete from a heap of concrete with your hands"],
    questions=["Is the person's hands visible in the photo?"],
    previous_questions=[[]],
    previous_answers=[[]],
)
pprint(metrics)

running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]


array([0.02783], dtype=float16)
tensor([[0.5977, 0.4021]], dtype=torch.float16)
["The person's hands are visible in the photo."]
["The person's hands are not visible in the photo."]


running generation (cuda:0): 0it [00:00, ?it/s]
running NLI (cuda:0): 100%|██████████| 1/1 [00:00<00:00, 20.18it/s]

{'informativeness': [0.027832],
 'informativeness_marginal': [0.027832],
 'informativeness_marginal_x_relevance_marginal': [0.010178],
 'relevance': [0.365723],
 'relevance_marginal': [0.365723],
 'rephrased_questions_no': ["The person's hands are not visible in the photo."],
 'rephrased_questions_yes': ["The person's hands are visible in the photo."]}
